### ISSUE TITLE
TODO main user page

### ISSUE THREAD

**Issue by lis0000057** [lis0000057/sometracker#5]
TODO:
//
- [ ] Добавить столбец с оптион типом продажи
- [ ] Добавить столбец ЛС
- [ ] Добавить столбец суммы
- [ ] Добавить скрипт расчета выполнения плана продаж
- [ ] Добавить маркер подтверждния продажи
